// ============================================================
// DRIVERS / TEAMS INFO — Datos fijos de pilotos y equipos
// Cambia solo cuando cambia un piloto/equipo (inicio de temporada).
// ============================================================

// ============ DRIVERS INFO (datos fijos) ============
const DRIVERS_INFO={
"VER":{name:"Max Verstappen",nat:"Países Bajos",flag:"nl",num:1,dob:"1997-09-30",debut:2015,bio:"Campeón del mundo 2021, 2022, 2023 y 2024. Hijo de Jos Verstappen. Debutó con Toro Rosso en 2015 como el piloto más joven en la historia de F1."},
"HAM":{name:"Lewis Hamilton",nat:"Reino Unido",flag:"gb",num:44,dob:"1985-01-07",debut:2007,bio:"Siete veces campeón del mundo (2008, 2014-2020). Récord de victorias y poles en F1. Debutó con McLaren en 2007 y pasó a Ferrari en 2025."},
"LEC":{name:"Charles Leclerc",nat:"Mónaco",flag:"mc",num:16,dob:"1997-10-16",debut:2018,bio:"Debutó con Sauber en 2018. Piloto de Ferrari desde 2019. Ahijado de Jules Bianchi."},
"SAI":{name:"Carlos Sainz Jr.",nat:"España",flag:"es",num:55,dob:"1994-09-01",debut:2015,bio:"Hijo del bicampeón mundial de rally. Debutó con Toro Rosso en 2015. Pasó por Renault, McLaren, Ferrari y Williams."},
"NOR":{name:"Lando Norris",nat:"Reino Unido",flag:"gb",num:4,dob:"1999-11-13",debut:2019,bio:"Debutó con McLaren en 2019. Campeón del mundo 2025 tras una batalla histórica con Verstappen."},
"PIA":{name:"Oscar Piastri",nat:"Australia",flag:"au",num:81,dob:"2001-04-06",debut:2023,bio:"Campeón de F3 y F2 consecutivos. Debutó con McLaren en 2023 tras disputa contractual con Alpine."},
"RUS":{name:"George Russell",nat:"Reino Unido",flag:"gb",num:63,dob:"1998-02-15",debut:2019,bio:"Campeón de GP3 y F2. Debutó con Williams en 2019. Titular en Mercedes desde 2022."},
"ANT":{name:"Kimi Antonelli",nat:"Italia",flag:"it",num:12,dob:"2006-08-25",debut:2025,bio:"Juvenil de Mercedes desde los 12 años. Saltó de F4 a F2 directo. Reemplazó a Hamilton en Mercedes en 2025. Récord del polesitter más joven de F1."},
"ALO":{name:"Fernando Alonso",nat:"España",flag:"es",num:14,dob:"1981-07-29",debut:2001,bio:"Bicampeón del mundo (2005, 2006) con Renault. Debutó en 2001. Regresó a F1 en 2021 con Alpine; titular de Aston Martin desde 2023."},
"STR":{name:"Lance Stroll",nat:"Canadá",flag:"ca",num:18,dob:"1998-10-29",debut:2017,bio:"Debutó con Williams en 2017. Titular de Aston Martin (equipo propiedad de su padre Lawrence) desde 2021."},
"GAS":{name:"Pierre Gasly",nat:"Francia",flag:"fr",num:10,dob:"1996-02-07",debut:2017,bio:"Debutó con Toro Rosso en 2017. Ganó el GP de Italia 2020. Se mudó a Alpine en 2023."},
"OCO":{name:"Esteban Ocon",nat:"Francia",flag:"fr",num:31,dob:"1996-09-17",debut:2016,bio:"Debutó con Manor en 2016. Ganó el GP de Hungría 2021 con Alpine. En Haas desde 2025."},
"HUL":{name:"Nico Hülkenberg",nat:"Alemania",flag:"de",num:27,dob:"1987-08-19",debut:2010,bio:"Debutó con Williams en 2010. Logró su primer podio en F1 en el GP de Reino Unido 2025 con Sauber. Pasa a Audi en 2026."},
"BEA":{name:"Oliver Bearman",nat:"Reino Unido",flag:"gb",num:87,dob:"2005-05-08",debut:2024,bio:"Debutó como suplente con Ferrari en Arabia Saudita 2024. Titular de Haas desde 2025. El número 87 combina su cumpleaños (8/5) y el de su hermano (7/8)."},
"ALB":{name:"Alex Albon",nat:"Tailandia",flag:"th",num:23,dob:"1996-03-23",debut:2019,bio:"Nacido en Londres, corre con licencia tailandesa. Debutó con Toro Rosso en 2019. En Williams desde 2022."},
"COL":{name:"Franco Colapinto",nat:"Argentina",flag:"ar",num:43,dob:"2003-05-27",debut:2024,bio:"Primer argentino en F1 desde Gastón Mazzacane (2001). Debutó con Williams a mitad de 2024. Reemplazó a Doohan en Alpine a mitad de 2025."},
"HAD":{name:"Isack Hadjar",nat:"Francia",flag:"fr",num:6,dob:"2004-09-28",debut:2025,bio:"Nacido en París, de ascendencia franco-argelina. Subcampeón de F2 2024. Debutó con Racing Bulls en 2025. Ascendió a Red Bull en 2026."},
"BOR":{name:"Gabriel Bortoleto",nat:"Brasil",flag:"br",num:5,dob:"2004-10-14",debut:2025,bio:"Campeón de F3 2023 y F2 2024 como debutante. Representado por A14 (Fernando Alonso). Debutó con Sauber en 2025, continúa con Audi en 2026."},
"LAW":{name:"Liam Lawson",nat:"Nueva Zelanda",flag:"nz",num:30,dob:"2002-02-11",debut:2023,bio:"Debutó como suplente con AlphaTauri en 2023. Titular de Racing Bulls desde 2025 tras su paso frustrado por Red Bull."},
"TSU":{name:"Yuki Tsunoda",nat:"Japón",flag:"jp",num:22,dob:"2000-05-11",debut:2021,bio:"Primer piloto japonés en F1 desde Kamui Kobayashi. Debutó con AlphaTauri en 2021. Promovido a Red Bull a mitad de 2025."},
"LIN":{name:"Arvid Lindblad",nat:"Reino Unido",flag:"gb",num:41,dob:"2007-08-08",debut:2026,bio:"Británico con ascendencia sueca e india. El único rookie del grid 2026. Ganador más joven de la historia en F2 y F3."},
"BOT":{name:"Valtteri Bottas",nat:"Finlandia",flag:"fi",num:77,dob:"1989-08-28",debut:2013,bio:"Subcampeón del mundo con Mercedes (2019, 2020). Ganó 10 GPs. Pasó por Williams, Mercedes y Sauber. Titular de Cadillac en 2026."},
"PER":{name:"Sergio Pérez",nat:"México",flag:"mx",num:11,dob:"1990-01-26",debut:2011,bio:"Debutó con Sauber en 2011. Compañero de Verstappen en Red Bull (2021-2024). Regresa a F1 con Cadillac en 2026."},
"RIC":{name:"Daniel Ricciardo",nat:"Australia",flag:"au",num:3,dob:"1989-07-01",debut:2011,bio:"Ganó 8 GPs con Red Bull. Pasó por HRT, Toro Rosso, Red Bull, Renault, McLaren y AlphaTauri. Última carrera en Singapur 2024."},
"MAG":{name:"Kevin Magnussen",nat:"Dinamarca",flag:"dk",num:20,dob:"1992-10-05",debut:2014,bio:"Debutó con McLaren y subió al podio en su primera carrera. Pasó por Renault, Haas (en dos etapas). Su última temporada completa fue 2024."},
"VET":{name:"Sebastian Vettel",nat:"Alemania",flag:"de",num:5,dob:"1987-07-03",debut:2007,bio:"Tetracampeón del mundo (2010-2013) con Red Bull. Ganó 53 GPs. Se retiró a fines de 2022 tras su paso por Aston Martin."},
"RAI":{name:"Kimi Räikkönen",nat:"Finlandia",flag:"fi",num:7,dob:"1979-10-17",debut:2001,bio:"Campeón del mundo 2007 con Ferrari. Ganó 21 GPs. Se retiró a fines de 2021 tras su paso final por Alfa Romeo."},
"GIO":{name:"Antonio Giovinazzi",nat:"Italia",flag:"it",num:99,dob:"1993-12-14",debut:2017,bio:"Corrió con Alfa Romeo entre 2019 y 2021. Posteriormente siguió carrera en WEC con Ferrari."},
"MAZ":{name:"Nikita Mazepin",nat:"Rusia",flag:"ru",num:9,dob:"1999-03-02",debut:2021,bio:"Corrió una única temporada en F1 con Haas en 2021. Su contrato fue rescindido tras la invasión rusa a Ucrania en 2022."},
"MCK":{name:"Mick Schumacher",nat:"Alemania",flag:"de",num:47,dob:"1999-03-22",debut:2021,bio:"Hijo de Michael Schumacher. Campeón de F2 2020. Corrió con Haas en 2021 y 2022."},
"KUB":{name:"Robert Kubica",nat:"Polonia",flag:"pl",num:88,dob:"1984-12-07",debut:2006,bio:"Ganador del GP de Canadá 2008. Regresó como suplente de Alfa Romeo en 2021 tras su accidente de rally de 2011."},
"LAT":{name:"Nicholas Latifi",nat:"Canadá",flag:"ca",num:6,dob:"1995-06-29",debut:2020,bio:"Corrió con Williams entre 2020 y 2022. Su accidente en Abu Dhabi 2021 marcó un hito histórico."},
"ZHO":{name:"Zhou Guanyu",nat:"China",flag:"cn",num:24,dob:"1999-05-30",debut:2022,bio:"Primer piloto chino en la historia de F1. Corrió con Alfa Romeo/Sauber entre 2022 y 2024."},
"DEV":{name:"Nyck de Vries",nat:"Países Bajos",flag:"nl",num:21,dob:"1995-02-06",debut:2022,bio:"Campeón de F2 2019 y de Fórmula E 2021. Corrió con AlphaTauri en 2023 antes de ser reemplazado por Ricciardo."},
"SAR":{name:"Logan Sargeant",nat:"Estados Unidos",flag:"us",num:2,dob:"2000-12-31",debut:2023,bio:"Primer piloto estadounidense en F1 desde Scott Speed. Corrió con Williams en 2023 y parte de 2024."},
"DOO":{name:"Jack Doohan",nat:"Australia",flag:"au",num:7,dob:"2003-01-20",debut:2024,bio:"Hijo del campeón de MotoGP Mick Doohan. Debutó en el GP de Abu Dhabi 2024 con Alpine. Reemplazado por Colapinto a mitad de 2025."},
"SEN":{name:"Ayrton Senna",nat:"Brasil",flag:"br",num:12,dob:"1960-03-21",debut:1984,bio:"Triple campeón del mundo (1988, 1990, 1991) con McLaren y Williams. Considerado uno de los mejores pilotos de la historia. Falleció en el GP de San Marino 1994."},
"BSE":{name:"Bruno Senna",nat:"Brasil",flag:"br",num:17,dob:"1983-10-15",debut:2010,bio:"Sobrino de Ayrton Senna. Debutó con HRT en 2010. Corrió con Renault (2011) y Williams (2012) antes de retirarse de la F1."},
// ── Era clásica (1990-2000s) — IDs nuevos post-disambiguación ──
"HAK":{name:"Mika Häkkinen",nat:"Finlandia",flag:"fi",num:3,dob:"1968-09-28",debut:1991,bio:"Bicampeón del mundo (1998, 1999) con McLaren. Ganó 20 GPs. Apodado 'El Cohete Volador'. Se retiró en 2001."},
"SAL":{name:"Mika Salo",nat:"Finlandia",flag:"fi",num:17,dob:"1966-11-30",debut:1994,bio:"Piloto de pruebas de Ferrari y sustituto en varios equipos. Corrió para Tyrrell, Arrows, BAR y Toyota entre 1994 y 2002."},
"FRE":{name:"Heinz-Harald Frentzen",nat:"Alemania",flag:"de",num:10,dob:"1967-05-18",debut:1994,bio:"Subcampeón del mundo 1997 con Williams. Ganó 3 GPs. Corrió para Sauber, Williams, Jordan, Prost y Arrows entre 1994 y 2003."},
"HER":{name:"Johnny Herbert",nat:"Reino Unido",flag:"gb",num:14,dob:"1964-06-25",debut:1989,bio:"Ganó 3 GPs (Silverstone y Monza 1995, Nürburgring 1999). Corrió para Benetton, Lotus, Sauber y Stewart entre 1989 y 2000."},
"GEN":{name:"Marc Gené",nat:"España",flag:"es",num:4,dob:"1974-03-29",debut:1999,bio:"Piloto de pruebas de Williams y Ferrari. Disputó temporadas con Minardi (1999) y Williams (2003-2004)."},
"JOS":{name:"Jos Verstappen",nat:"Países Bajos",flag:"nl",num:16,dob:"1972-03-04",debut:1994,bio:"Padre de Max Verstappen. Debutó en 1994 con Benetton junto a Michael Schumacher. Corrió para varios equipos entre 1994 y 2003."},
"JVR":{name:"Jean-Éric Vergne",nat:"Francia",flag:"fr",num:25,dob:"1990-04-25",debut:2012,bio:"Corrió con Toro Rosso entre 2012 y 2014. Posteriormente ganó dos títulos de Fórmula E (2018, 2019)."},
"SCH":{name:"Ralf Schumacher",nat:"Alemania",flag:"de",num:4,dob:"1975-06-30",debut:1997,bio:"Hermano de Michael Schumacher. Ganó 6 GPs con Williams. Corrió para Jordan, Williams y Toyota entre 1997 y 2007."},
"JMG":{name:"Jan Magnussen",nat:"Dinamarca",flag:"dk",num:17,dob:"1973-07-04",debut:1995,bio:"Padre de Kevin Magnussen. Subcampeón de F3000 1994. Debutó con McLaren en 1995, luego corrió para Stewart."},
"PJR":{name:"Nelson Piquet Jr.",nat:"Brasil",flag:"br",num:8,dob:"1985-07-25",debut:2008,bio:"Hijo de Nelson Piquet. Corrió con Renault en 2008-2009. Primer campeón de la Fórmula E (2014-2015). Involucrado en el 'crashgate' del GP de Singapur 2008."},
"SBD":{name:"Sébastien Bourdais",nat:"Francia",flag:"fr",num:11,dob:"1979-02-28",debut:2008,bio:"Cuádruple campeón de la Champ Car (2004-2007). Corrió con Toro Rosso en 2008 y parte de 2009 antes de ser reemplazado."},
"RDB":{name:"Robert Doornbos",nat:"Países Bajos",flag:"nl",num:17,dob:"1981-09-23",debut:2005,bio:"Corrió con Minardi y Red Bull entre 2005 y 2006. Luego hizo carrera en IndyCar."},
"RHA":{name:"Rio Haryanto",nat:"Indonesia",flag:"id",num:88,dob:"1993-01-22",debut:2016,bio:"Primer indonesio en F1. Corrió con Manor en 2016 financiado por patrocinadores del gobierno indonesio."},
"GMZ":{name:"Gastón Mazzacane",nat:"Argentina",flag:"ar",num:21,dob:"1975-05-08",debut:2000,bio:"Primer argentino en F1 desde 1981. Corrió con Minardi y Prost en 2000-2001."},
"ALR":{name:"Michele Alboreto",nat:"Italia",flag:"it",num:7,dob:"1956-12-23",debut:1981,bio:"Subcampeón del mundo 1985 con Ferrari. Ganó 5 GPs. Corrió en F1 entre 1981 y 1994. Falleció en 2001 durante una prueba en Lausitzring."},
"CAL":{name:"Christijan Albers",nat:"Países Bajos",flag:"nl",num:21,dob:"1979-04-16",debut:2005,bio:"Corrió con Minardi/MF1 y Spyker entre 2005 y 2007. Hijo de un exitoso piloto de rally holandés."},
"YOO":{name:"Alex Yoong",nat:"Malasia",flag:"my",num:21,dob:"1976-07-20",debut:2001,bio:"Primer piloto malayo en F1. Corrió con Minardi en 2001 y 2002."},
"MCN":{name:"Allan McNish",nat:"Reino Unido",flag:"gb",num:22,dob:"1969-12-29",debut:2002,bio:"Corrió una única temporada completa en F1 con Toyota en 2002. Tres veces ganador de Le Mans (1998, 2008, 2013)."},
"PBR":{name:"Paolo Barilla",nat:"Italia",flag:"it",num:23,dob:"1961-04-20",debut:1989,bio:"Heredero de la empresa de pasta Barilla. Corrió con Minardi en 1989 y 1990."},
"FBZ":{name:"Fabrizio Barbazza",nat:"Italia",flag:"it",num:22,dob:"1963-04-02",debut:1991,bio:"Corrió con AGS en 1991 y con Minardi en 1993."},
"EBN":{name:"Éric Bernard",nat:"Francia",flag:"fr",num:25,dob:"1964-08-24",debut:1989,bio:"Subcampeón de F3000 1988. Corrió con Larrousse y Ligier entre 1989 y 1994."},
"JBL":{name:"Jean-Christophe Boullion",nat:"Francia",flag:"fr",num:29,dob:"1969-12-27",debut:1995,bio:"Campeón de F3000 1994. Corrió para Sauber en 1995."},
"DBM":{name:"David Brabham",nat:"Australia",flag:"au",num:23,dob:"1965-09-05",debut:1990,bio:"Hijo del tricampeón Sir Jack Brabham. Corrió con Brabham en 1990 y con Simtek en 1994."},
"PCH":{name:"Pedro Chaves",nat:"Portugal",flag:"pt",num:30,dob:"1965-02-27",debut:1991,bio:"Piloto portugués que corrió con Coloni en 1991."},
"ACH":{name:"Andrea Chiesa",nat:"Suiza",flag:"ch",num:21,dob:"1964-05-06",debut:1992,bio:"Piloto suizo que corrió con Fondmetal en 1992."},
"PFT":{name:"Pietro Fittipaldi",nat:"Brasil",flag:"br",num:51,dob:"1996-06-25",debut:2020,bio:"Nieto de Emerson Fittipaldi. Corrió como suplente de Haas en 2020. Corredor habitual en IndyCar."},
"GBR":{name:"Gianmaria Bruni",nat:"Italia",flag:"it",num:20,dob:"1981-05-30",debut:2004,bio:"Corrió con Minardi en 2004. Posteriormente fue piloto oficial de Ferrari en el GT World Challenge."},
"GPA":{name:"Giorgio Pantano",nat:"Italia",flag:"it",num:17,dob:"1979-02-08",debut:2004,bio:"Subcampeón de F3000 en 2003. Corrió con Jordan en 2004."},
"OGR":{name:"Olivier Grouillard",nat:"Francia",flag:"fr",num:25,dob:"1958-09-02",debut:1989,bio:"Corrió con Ligier, Osella, Fondmetal y Tyrrell entre 1989 y 1992."},
"JLA":{name:"Jan Lammers",nat:"Países Bajos",flag:"nl",num:12,dob:"1956-06-02",debut:1979,bio:"Ganador de Le Mans 1988. Corrió brevemente con March en 1992 como sustituto."},
"TMQ":{name:"Tarso Marques",nat:"Brasil",flag:"br",num:22,dob:"1976-01-19",debut:1996,bio:"Corrió con Minardi en 1996-1997 y 2001."},
"AMO":{name:"Andrea Montermini",nat:"Italia",flag:"it",num:20,dob:"1964-05-30",debut:1994,bio:"Corrió con Simtek y Pacific entre 1994 y 1996."},
"GMO":{name:"Giovanni Morbidelli",nat:"Italia",flag:"it",num:23,dob:"1968-01-13",debut:1991,bio:"Corrió para varios equipos menores (Ferrari suplente, Footwork, Minardi) entre 1991 y 1997."},
"SNJ":{name:"Satoru Nakajima",nat:"Japón",flag:"jp",num:11,dob:"1953-02-23",debut:1987,bio:"Primer japonés en correr de forma regular en F1. Corrió con Lotus y Tyrrell entre 1987 y 1991. Padre de Kazuki Nakajima."},
"SNA":{name:"Shinji Nakano",nat:"Japón",flag:"jp",num:11,dob:"1971-04-01",debut:1997,bio:"Corrió con Prost en 1997 y Minardi en 1998."},
"ENS":{name:"Emanuele Naspetti",nat:"Italia",flag:"it",num:22,dob:"1968-02-24",debut:1992,bio:"Corrió con March y Jordan en 1992-1993."},
"RRS":{name:"Ricardo Rosset",nat:"Brasil",flag:"br",num:15,dob:"1968-07-27",debut:1996,bio:"Corrió con Footwork, Lola y Tyrrell entre 1996 y 1998."},
"BSN":{name:"Bernd Schneider",nat:"Alemania",flag:"de",num:30,dob:"1964-07-20",debut:1988,bio:"Corrió con Zakspeed, Arrows y Footwork en F1 entre 1988 y 1990. Tuvo mayor éxito en el DTM, ganando 5 títulos."},
"DSC":{name:"Domenico Schiattarella",nat:"Italia",flag:"it",num:23,dob:"1967-11-17",debut:1994,bio:"Corrió con Simtek en 1994 y con Forti en 1995."},
"SSZ":{name:"Sébastien Sarrazin",nat:"Francia",flag:"fr",num:9,dob:"1975-05-02",debut:1999,bio:"Corrió un único GP con Minardi en 1999 (Francia). Tuvo más éxito en el WEC y Le Mans."}
,
"JON":{"name":"Alan Jones","nat":"Australia","flag":"au","num":27,"dob":"1946-11-02","debut":1975,"bio":"Campeón del mundo 1980 con Williams. Estilo agresivo y directo. Se retiró en 1981 pero volvió brevemente en 1983."},
"PIQ":{"name":"Nelson Piquet","nat":"Brasil","flag":"br","num":5,"dob":"1952-08-17","debut":1978,"bio":"Tricampeón del mundo (1981, 1983, 1987). Apodado O Baixinho. Compitió con Brabham, Williams y Lotus."},
"REU":{"name":"Carlos Reutemann","nat":"Argentina","flag":"ar","num":11,"dob":"1942-04-12","debut":1972,"bio":"Piloto argentino subcampeón en 1981. Conocido por su velocidad y sensibilidad con el coche. Se retiró en 1982."},
"LAF":{"name":"Jacques Laffite","nat":"Francia","flag":"fr","num":26,"dob":"1943-11-21","debut":1974,"bio":"Piloto de Ligier durante la mayor parte de su carrera. Sufrió lesiones graves en el accidente múltiple de 1986."},
"DPR":{"name":"Didier Pironi","nat":"Francia","flag":"fr","num":28,"dob":"1952-03-26","debut":1978,"bio":"Piloto francés que casi ganó el mundial 1982 con Ferrari. Su carrera se truncó por un accidente en el GP de Alemania 1982."},
"ARN":{"name":"René Arnoux","nat":"Francia","flag":"fr","num":49,"dob":"1948-07-04","debut":1978,"bio":"Conocido por su batalla con Villeneuve en Dijon 1979. Ganó 7 GPs con Renault y Ferrari."},
"EDA":{"name":"Elio de Angelis","nat":"Italia","flag":"it","num":11,"dob":"1958-03-26","debut":1979,"bio":"Pianista y piloto italiano. Compitió con Lotus durante la mayor parte de su carrera. Falleció en pruebas en 1986."},
"GVI":{"name":"Gilles Villeneuve","nat":"Canadá","flag":"ca","num":27,"dob":"1950-01-18","debut":1977,"bio":"Uno de los pilotos más espectaculares de la historia. Piloto de Ferrari. Falleció en clasificación en Bélgica 1982."},
"WAT":{"name":"John Watson","nat":"Reino Unido","flag":"gb","num":7,"dob":"1946-05-04","debut":1973,"bio":"Piloto norirlandés que ganó 5 GPs con McLaren. Conocido por su gran remontada desde la posición 22 en EE.UU. 1983."},
"PAT":{"name":"Riccardo Patrese","nat":"Italia","flag":"it","num":6,"dob":"1954-04-17","debut":1977,"bio":"Piloto italiano que disputó 256 GPs, récord en su época. Compitió con Arrows, Brabham, Alfa Romeo y Williams."},
"SCK":{"name":"Jody Scheckter","nat":"Sudáfrica","flag":"za","num":1,"dob":"1950-01-29","debut":1972,"bio":"Campeón del mundo 1979 con Ferrari. Se retiró en 1980 tras una difícil temporada con el equipo italiano."},
"KEK":{"name":"Keke Rosberg","nat":"Finlandia","flag":"fi","num":6,"dob":"1948-12-06","debut":1978,"bio":"Campeón del mundo 1982 con Williams. Padre de Nico Rosberg. Conocido por su conducción agresiva y sus remontadas."},
"PRO":{"name":"Alain Prost","nat":"Francia","flag":"fr","num":1,"dob":"1955-02-24","debut":1980,"bio":"El Profesor. Cuatro veces campeón del mundo (1985, 1986, 1989, 1993). Gran rivalidad con Senna en McLaren."},
"LAU":{"name":"Niki Lauda","nat":"Austria","flag":"at","num":1,"dob":"1949-02-22","debut":1971,"bio":"Tricampeón del mundo (1975, 1977, 1984). Sobrevivió un terrible accidente en el Nürburgring 1976. Se retiró en 1985."},
"MAN":{"name":"Nigel Mansell","nat":"Reino Unido","flag":"gb","num":5,"dob":"1953-08-08","debut":1980,"bio":"Campeón del mundo 1992. El León. Conocido por su conducción agresiva y su rivalidad con Senna y Prost."},
"BER":{"name":"Gerhard Berger","nat":"Austria","flag":"at","num":28,"dob":"1959-08-27","debut":1984,"bio":"Piloto austríaco con 10 victorias en F1. Compañero de Senna en McLaren. Corrió con Arrows, Benetton, Ferrari y McLaren."},
"NAN":{"name":"Alessandro Nannini","nat":"Italia","flag":"it","num":12,"dob":"1959-07-07","debut":1986,"bio":"Ganó el GP de Japón 1989 con Benetton. Su carrera se truncó tras un accidente de helicóptero en 1990."},
"CHE":{"name":"Eddie Cheever","nat":"EE.UU.","flag":"us","num":8,"dob":"1958-01-10","debut":1978,"bio":"Piloto italoamericano que disputó 132 GPs. Corrió con Renault, Alfa Romeo, Lola y Arrows."},
"BOU":{"name":"Thierry Boutsen","nat":"Bélgica","flag":"be","num":5,"dob":"1957-07-13","debut":1983,"bio":"Piloto belga con 3 victorias en F1, todas en condiciones de lluvia. Compitió con Arrows, Benetton y Williams."},
"WAR":{"name":"Derek Warwick","nat":"Reino Unido","flag":"gb","num":16,"dob":"1954-08-27","debut":1981,"bio":"Piloto británico que nunca consiguió un puesto en un equipo top pese a sus méritos. Compitió con Toleman, Renault, Brabham y Arrows."},
"TAM":{"name":"Patrick Tambay","nat":"Francia","flag":"fr","num":27,"dob":"1949-06-25","debut":1977,"bio":"Sustituyó a Villeneuve en Ferrari en 1982. Ganó 2 GPs con la Scuderia."},
"CES":{"name":"Andrea de Cesaris","nat":"Italia","flag":"it","num":22,"dob":"1959-05-31","debut":1980,"bio":"Piloto italiano con 208 GPs disputados. Conocido por sus accidentes al inicio de su carrera. Nunca logró ganar un GP."},
"JOH":{"name":"Stefan Johansson","nat":"Suecia","flag":"se","num":16,"dob":"1956-09-08","debut":1983,"bio":"Piloto sueco que compitió con Ferrari y McLaren. Dos segundos puestos en 1985 con Ferrari."},
"CAF":{"name":"Alex Caffi","nat":"Italia","flag":"it","num":23,"dob":"1963-03-18","debut":1987,"bio":"Piloto italiano que compitió con Osella, Dallara y Arrows."},
"GAC":{"name":"Bertrand Gachot","nat":"Bélgica","flag":"be","num":14,"dob":"1962-12-23","debut":1989,"bio":"Piloto belga-luxemburgués. Compitió con Onyx y Rial. También conocido por el incidente que le impidió pilotar el Jordan 1991."},
"GIA":{"name":"Bruno Giacomelli","nat":"Italia","flag":"it","num":22,"dob":"1952-09-10","debut":1977,"bio":"Piloto italiano que compitió principalmente con Alfa Romeo. Logró la pole en el GP de EE.UU. 1980."},
"DAL":{"name":"Derek Daly","nat":"Irlanda","flag":"ie","num":30,"dob":"1953-03-11","debut":1978,"bio":"Piloto irlandés que compitió con Tyrrell, March, Theodore y Williams."},
"PIZ":{"name":"Emanuele Pirro","nat":"Italia","flag":"it","num":17,"dob":"1962-01-12","debut":1989,"bio":"Piloto italiano que compitió con Benetton. Exitoso también en el Campeonato Mundial de Endurance."},
"FIT":{"name":"Emerson Fittipaldi","nat":"Brasil","flag":"br","num":1,"dob":"1946-12-12","debut":1970,"bio":"Bicampeón del mundo (1972, 1974). Fundó el equipo Fittipaldi. Se retiró de la F1 en 1980."},
"TAR":{"name":"Gabriele Tarquini","nat":"Italia","flag":"it","num":21,"dob":"1962-03-05","debut":1987,"bio":"Piloto italiano que compitió con Osella, Coloni y AGS. Exitoso posteriormente en las series de turismo."},
"FOI":{"name":"Gregor Foitek","nat":"Suiza","flag":"ch","num":10,"dob":"1965-03-27","debut":1989,"bio":"Piloto suizo que compitió con Euro Brun y Rial en 1989."},
"CAP":{"name":"Ivan Capelli","nat":"Italia","flag":"it","num":16,"dob":"1963-05-24","debut":1985,"bio":"Piloto italiano que compitió con Tyrrell, AGS, March y Ferrari. Estuvo cerca de ganar en Portugal 1990."},
"ALE":{"name":"Jean Alesi","nat":"Francia","flag":"fr","num":27,"dob":"1964-06-11","debut":1989,"bio":"Piloto francés de origen siciliano. Debutó con Tyrrell en 1989. Ganó su único GP en Canadá 1995 con Ferrari."},
"JPJ":{"name":"Jean-Pierre Jabouille","nat":"Francia","flag":"fr","num":15,"dob":"1942-10-01","debut":1975,"bio":"Primer piloto en ganar con motor turbocargado (Francia 1979, Renault). Sufrió graves lesiones en Canadá 1980."},
"JAR":{"name":"Jean-Pierre Jarier","nat":"Francia","flag":"fr","num":21,"dob":"1946-07-10","debut":1971,"bio":"Veloz piloto francés apodado Mr. Nobody. Nunca ganó un GP pese a estar cerca en varias ocasiones."},
"PAL":{"name":"Jonathan Palmer","nat":"Reino Unido","flag":"gb","num":3,"dob":"1956-11-07","debut":1983,"bio":"Piloto y médico británico. Compitió con RAM, Zakspeed y Tyrrell. Actualmente promotor del motorsport."},
"BAI":{"name":"Julian Bailey","nat":"Reino Unido","flag":"gb","num":11,"dob":"1961-10-09","debut":1988,"bio":"Piloto británico que disputó varios GPs con Tyrrell en 1988."},
"WIN":{"name":"Manfred Winkelhock","nat":"Alemania","flag":"de","num":35,"dob":"1952-10-06","debut":1980,"bio":"Piloto alemán que compitió con ATS, Arrows, Brabham y RAM. Falleció en Mosport en 1985."},
"LAR":{"name":"Nicola Larini","nat":"Italia","flag":"it","num":15,"dob":"1964-03-19","debut":1987,"bio":"Piloto italiano que compitió con Coloni y Osella en los 80s. Exitoso posteriormente en touring cars."},
"SMD":{"name":"Stefano Modena","nat":"Italia","flag":"it","num":12,"dob":"1963-05-12","debut":1987,"bio":"Piloto italiano que compitió con Euro Brun, Brabham y Tyrrell."},
"DON":{"name":"Martin Donnelly","nat":"Reino Unido","flag":"gb","num":19,"dob":"1964-03-26","debut":1989,"bio":"Piloto norirlandés que tuvo un grave accidente durante los entrenamientos del GP de España 1990 en Jerez."},
"BRU":{"name":"Martin Brundle","nat":"Reino Unido","flag":"gb","num":7,"dob":"1959-06-01","debut":1984,"bio":"Piloto británico con Tyrrell, Zakspeed, Williams, Brabham y más. Ahora comentarista de Sky Sports F1."},
"GUG":{"name":"Maurício Gugelmin","nat":"Brasil","flag":"br","num":15,"dob":"1963-04-20","debut":1988,"bio":"Piloto brasileño que compitió con March y Jordan. Compañero de Senna en karting."},
"BEL":{"name":"Stefan Bellof","nat":"Alemania","flag":"de","num":20,"dob":"1957-11-20","debut":1984,"bio":"Uno de los pilotos más prometedores de su generación. Falleció en Spa 1985. Tenía el récord del Nürburgring."},
"ALL":{"name":"Philippe Alliot","nat":"Francia","flag":"fr","num":24,"dob":"1954-07-27","debut":1984,"bio":"Piloto francés que compitió con RAM, Larrousse y Ligier. Excelente en resistencia."},
"MOR":{"name":"Roberto Moreno","nat":"Brasil","flag":"br","num":20,"dob":"1959-02-11","debut":1987,"bio":"Piloto brasileño que sustituyó a Schumacher en Benetton en 1991."},
"BRA":{"name":"Vittorio Brambilla","nat":"Italia","flag":"it","num":9,"dob":"1937-11-11","debut":1974,"bio":"El Gorila de Monza. Ganó el GP de Austria 1975 con March. Se retiró en 1980."},
"PCG":{"name":"Piercarlo Ghinzani","nat":"Italia","flag":"it","num":21,"dob":"1952-01-16","debut":1981,"bio":"Piloto italiano que compitió con Osella, Toleman, Ligier y Zakspeed durante los años 80."},
"PMT":{"name":"Pierluigi Martini","nat":"Italia","flag":"it","num":25,"dob":"1961-04-23","debut":1984,"bio":"Piloto italiano que compitió principalmente con Minardi, logrando varios puntos con el equipo."},
"MSR":{"name":"Marc Surer","nat":"Suiza","flag":"ch","num":29,"dob":"1951-09-18","debut":1979,"bio":"Piloto suizo que compitió con ATS, Ensign, Arrows y Brabham. Un accidente de rally en 1986 terminó su carrera."},
"MAA":{"name":"Mario Andretti","nat":"EE.UU.","flag":"us","num":11,"dob":"1940-02-28","debut":1968,"bio":"Campeón del mundo 1978 con Lotus. Leyenda del automovilismo americano. Corrió también en IndyCar y NASCAR."},
"CAM":{"name":"Adrián Campos","nat":"España","flag":"es","num":26,"dob":"1960-06-17","debut":1987,"bio":"Primer piloto español en F1 desde 1977. Compitió con Minardi. Fundó la academia que llevó a Alonso al éxito."},
"AGU":{"name":"Aguri Suzuki","nat":"Japón","flag":"jp","num":11,"dob":"1960-09-08","debut":1988,"bio":"Piloto japonés que compitió con Zakspeed y Larrousse. Logró el tercer puesto en el GP de Japón 1990."},
"ABR":{"name":"Allen Berg","nat":"Canadá","flag":"ca","num":30,"dob":"1961-08-01","debut":1986,"bio":"Piloto canadiense que disputó varios GPs con Osella en 1986."},
"GBB":{"name":"Beppe Gabbiani","nat":"Italia","flag":"it","num":30,"dob":"1957-01-02","debut":1978,"bio":"Piloto italiano que compitió con Osella en los años 80."},
"HNT":{"name":"Brian Henton","nat":"Reino Unido","flag":"gb","num":36,"dob":"1946-09-19","debut":1975,"bio":"Piloto británico que compitió con Toleman, Tyrrell y Arrows."},
"CSS":{"name":"Chico Serra","nat":"Brasil","flag":"br","num":31,"dob":"1957-02-03","debut":1981,"bio":"Piloto brasileño que compitió con Fittipaldi y Arrows."},
"CDN":{"name":"Christian Danner","nat":"Alemania","flag":"de","num":30,"dob":"1958-04-04","debut":1985,"bio":"Piloto alemán que compitió con Zakspeed, Osella, Arrows y Rial."},
"REG":{"name":"Clay Regazzoni","nat":"Suiza","flag":"ch","num":0,"dob":"1939-09-05","debut":1970,"bio":"Leyenda suiza de los 70s. Ganó 5 GPs. Un accidente en Long Beach 1980 lo dejó paralítico."},
"CFB":{"name":"Corrado Fabi","nat":"Italia","flag":"it","num":23,"dob":"1961-04-12","debut":1983,"bio":"Piloto italiano, hermano de Teo Fabi. Compitió con Osella y Brabham."},
"DSU":{"name":"Danny Sullivan","nat":"EE.UU.","flag":"us","num":84,"dob":"1950-03-09","debut":1983,"bio":"Piloto americano que disputó la temporada 1983 con Tyrrell. Mayor éxito en CART/IndyCar."},
"DKN":{"name":"Dave Kennedy","nat":"Irlanda","flag":"ie","num":35,"dob":"1953-01-25","debut":1980,"bio":"Piloto irlandés que disputó algunos GPs con Shadow en 1980."},
"DWI":{"name":"Desiré Wilson","nat":"Sudáfrica","flag":"za","num":22,"dob":"1953-11-26","debut":1980,"bio":"Primera mujer en ganar una carrera de Fórmula 1 (Aurora AFX, Brands Hatch 1980). Disputó un GP con Williams."},
"EMV":{"name":"Emilio de Villota","nat":"España","flag":"es","num":30,"dob":"1946-07-26","debut":1977,"bio":"Piloto español que intentó clasificarse en varios GPs. Padre de María de Villota."},
"ENB":{"name":"Enrico Bertaggia","nat":"Italia","flag":"it","num":36,"dob":"1964-09-19","debut":1989,"bio":"Piloto italiano que disputó algunos GPs con Coloni en 1989."},
"FHE":{"name":"François Hesnault","nat":"Francia","flag":"fr","num":25,"dob":"1956-12-30","debut":1984,"bio":"Piloto francés que compitió con Ligier, Brabham y Renault."},
"FFO":{"name":"Franco Forini","nat":"Suiza","flag":"ch","num":32,"dob":"1958-09-05","debut":1987,"bio":"Piloto suizo que disputó algunos GPs con Osella en 1987."},
"GLE":{"name":"Geoff Lees","nat":"Reino Unido","flag":"gb","num":30,"dob":"1951-05-01","debut":1980,"bio":"Piloto británico que disputó algunos GPs con varios equipos en los 80s."},
"GFR":{"name":"Giorgio Francia","nat":"Italia","flag":"it","num":31,"dob":"1947-05-01","debut":1981,"bio":"Piloto italiano que disputó algunos GPs con Osella."},
"HAE":{"name":"Harald Ertl","nat":"Austria","flag":"at","num":35,"dob":"1948-08-31","debut":1976,"bio":"Piloto austríaco que compitió con Hesketh y ATS. Amigo de Lauda que filmó su accidente en 1976."},
"HRB":{"name":"Hector Rebaque","nat":"México","flag":"mx","num":30,"dob":"1956-02-05","debut":1977,"bio":"Piloto mexicano que compitió con Brabham en 1981."},
"HRO":{"name":"Huub Rothengatter","nat":"Países Bajos","flag":"nl","num":14,"dob":"1954-10-08","debut":1984,"bio":"Piloto holandés que compitió con Spirit, Osella y Zakspeed."},
"JLS":{"name":"Jean-Louis Schlesser","nat":"Francia","flag":"fr","num":22,"dob":"1948-09-12","debut":1988,"bio":"Disputó un único GP con Williams en 1988, chocando con Senna cuando este lideraba en Monza."},
"JGA":{"name":"Jo Gartner","nat":"Austria","flag":"at","num":30,"dob":"1954-01-24","debut":1984,"bio":"Piloto austríaco que compitió con Osella. Falleció en las 24 Horas de Le Mans de 1986."},
"JWI":{"name":"Joachim Winkelhock","nat":"Alemania","flag":"de","num":32,"dob":"1960-10-24","debut":1989,"bio":"Piloto alemán, hermano de Manfred Winkelhock. Disputó algunos GPs con AGS."},
"KCG":{"name":"Kevin Cogan","nat":"EE.UU.","flag":"us","num":30,"dob":"1956-03-31","debut":1980,"bio":"Piloto americano que disputó algunos GPs con Tyrrell y Williams."},
"NAK":{"name":"Satoru Nakajima","nat":"Japón","flag":"jp","num":11,"dob":"1953-02-23","debut":1987,"bio":"Primer piloto japonés en competir en F1 de forma regular. Compitió con Lotus y Tyrrell."},
"OSE":{"name":"Oscar Larrauri","nat":"Argentina","flag":"ar","num":30,"dob":"1954-08-06","debut":1988,"bio":"Piloto argentino que disputó algunos GPs con Euro Brun en 1988."},
"PDV":{"name":"Patrick Depailler","nat":"Francia","flag":"fr","num":4,"dob":"1944-08-09","debut":1972,"bio":"Piloto francés con Tyrrell y Ligier. Ganó 2 GPs. Falleció en un accidente en Hockenheim 1980."},
"PFR":{"name":"Paolo Barilla","nat":"Italia","flag":"it","num":30,"dob":"1961-04-20","debut":1989,"bio":"Piloto italiano del famoso linaje de pasta. Disputó algunos GPs con Minardi."},
"RPL":{"name":"Riccardo Paletti","nat":"Italia","flag":"it","num":23,"dob":"1958-06-15","debut":1982,"bio":"Piloto italiano que falleció en el accidente de la salida del GP de Canadá 1982 con Osella."},
"RRA":{"name":"Raul Boesel","nat":"Brasil","flag":"br","num":30,"dob":"1957-12-04","debut":1982,"bio":"Piloto brasileño que compitió con March y Ligier. Exitoso en CART/IndyCar."},
"SEK":{"name":"Slim Borgudd","nat":"Suecia","flag":"se","num":30,"dob":"1946-11-25","debut":1981,"bio":"Piloto sueco músico de ABBA. Compitió con ATS en 1981."},
"TFB":{"name":"Teo Fabi","nat":"Italia","flag":"it","num":23,"dob":"1955-03-09","debut":1982,"bio":"Piloto italiano, hermano de Corrado Fabi. Compitió con Toleman, Brabham y Benetton."},
"TNE":{"name":"Tiff Needell","nat":"Reino Unido","flag":"gb","num":35,"dob":"1951-10-29","debut":1980,"bio":"Piloto británico que disputó un único GP con Ensign en 1980. Conocido por sus apariciones en Top Gear."},
"TBY":{"name":"Tommy Byrne","nat":"Irlanda","flag":"ie","num":35,"dob":"1958-05-06","debut":1982,"bio":"Piloto irlandés que disputó algunos GPs con Theodore en 1982."},
"VWE":{"name":"Volker Weidler","nat":"Alemania","flag":"de","num":35,"dob":"1962-03-18","debut":1989,"bio":"Piloto alemán que compitió con Rial en 1989. Exitoso en la clase C del Campeonato Mundial de Resistencia."},
"YDA":{"name":"Yannick Dalmas","nat":"Francia","flag":"fr","num":23,"dob":"1961-07-28","debut":1987,"bio":"Piloto francés que compitió con Larrousse y AGS. Ganó Le Mans en tres ocasiones."},
"DEP":{"name":"Patrick Depailler","nat":"Francia","flag":"fr","num":4,"dob":"1944-08-09","debut":1972,"bio":"Piloto francés con Tyrrell y Ligier. Ganó 2 GPs. Falleció en un accidente en Hockenheim 1980."},
"RGO":{"name":"Roberto Guerrero","nat":"Colombia","flag":"co","num":30,"dob":"1958-11-16","debut":1982,"bio":"Piloto colombiano que compitió con Ensign y Theodore. Exitoso también en IndyCar."},
"RKG":{"name":"Rupert Keegan","nat":"Reino Unido","flag":"gb","num":38,"dob":"1955-02-26","debut":1977,"bio":"Piloto británico que disputó algunos GPs con Williams y March."},
"SSB":{"name":"Slim Borgudd","nat":"Suecia","flag":"se","num":30,"dob":"1946-11-25","debut":1981,"bio":"Piloto sueco músico de ABBA. Compitió con ATS en 1981."}
,
"JMO":{"name":"Jochen Mass","nat":"Alemania","flag":"de","num":30,"dob":"1946-09-30","debut":1973,"bio":"Piloto alemán que compitió con McLaren, Arrows y March. Corrió en F1 hasta 1982."},
"KCO":{"name":"Kevin Cogan","nat":"EE.UU.","flag":"us","num":30,"dob":"1956-03-31","debut":1980,"bio":"Piloto americano que disputó algunos GPs con Tyrrell y Williams."},
"MTH":{"name":"Mike Thackwell","nat":"Nueva Zelanda","flag":"nz","num":35,"dob":"1961-03-30","debut":1980,"bio":"Joven piloto neozelandés que disputó algunos GPs con Tyrrell y RAM."},
"RKE":{"name":"Rupert Keegan","nat":"Reino Unido","flag":"gb","num":38,"dob":"1955-02-26","debut":1977,"bio":"Piloto británico que disputó algunos GPs con Williams, Hesketh y March."},
"RZU":{"name":"Ricardo Zunino","nat":"Argentina","flag":"ar","num":22,"dob":"1949-04-13","debut":1979,"bio":"Piloto argentino que compitió con Brabham y Tyrrell en 1980-1981."},
"SSO":{"name":"Stephen South","nat":"Reino Unido","flag":"gb","num":35,"dob":"1952-10-19","debut":1980,"bio":"Piloto británico que disputó un único GP con McLaren en 1980."},
"MGA":{"name":"Miguel Ángel Guerra","nat":"Argentina","flag":"ar","num":30,"dob":"1953-08-31","debut":1981,"bio":"Piloto argentino que disputó algunos GPs con Osella en 1981."},
"RLO":{"name":"Ricardo Londoño","nat":"Colombia","flag":"co","num":30,"dob":"1950-08-15","debut":1981,"bio":"Piloto colombiano que disputó un único GP con Ensign en 1981."},
"SST":{"name":"Siegfried Stohr","nat":"Italia","flag":"it","num":32,"dob":"1952-10-10","debut":1981,"bio":"Piloto italiano que compitió con Arrows en 1981."},
"MBL":{"name":"Mauro Baldi","nat":"Italia","flag":"it","num":23,"dob":"1954-01-31","debut":1982,"bio":"Piloto italiano que compitió con Arrows y Alfa Romeo. Exitoso también en las 24 Horas de Le Mans."},
"RBE":{"name":"Raul Boesel","nat":"Brasil","flag":"br","num":30,"dob":"1957-12-04","debut":1982,"bio":"Piloto brasileño que compitió con March y Ligier. Exitoso en CART/IndyCar."},
"RGU":{"name":"Roberto Guerrero","nat":"Colombia","flag":"co","num":30,"dob":"1958-11-16","debut":1982,"bio":"Piloto colombiano que compitió con Ensign y Theodore. Exitoso también en IndyCar."},
"TFA":{"name":"Teo Fabi","nat":"Italia","flag":"it","num":23,"dob":"1955-03-09","debut":1982,"bio":"Piloto italiano, hermano de Corrado Fabi. Compitió con Toleman, Brabham y Benetton."},
"JCE":{"name":"Johnny Cecotto","nat":"Venezuela","flag":"ve","num":31,"dob":"1956-01-25","debut":1983,"bio":"Campeón mundial de motos (350cc, 1975). Disputó algunos GPs con Toleman en 1983."},
"JDU":{"name":"Johnny Dumfries","nat":"Reino Unido","flag":"gb","num":33,"dob":"1958-04-26","debut":1986,"bio":"Piloto escocés (Lord Dumfries) que compitió con Lotus en 1986 como compañero de Senna."},
"PFA":{"name":"Pascal Fabre","nat":"Francia","flag":"fr","num":14,"dob":"1960-01-09","debut":1987,"bio":"Piloto francés que disputó la temporada 1987 con AGS."},
"LPS":{"name":"Luis Pérez-Sala","nat":"España","flag":"es","num":27,"dob":"1959-05-15","debut":1988,"bio":"Piloto español que compitió con Minardi en 1988-1989."},
"OLA":{"name":"Oscar Larrauri","nat":"Argentina","flag":"ar","num":30,"dob":"1954-08-06","debut":1988,"bio":"Piloto argentino que disputó algunos GPs con Euro Brun en 1988."},
"PHR":{"name":"Pierre-Henri Raphanel","nat":"Francia","flag":"fr","num":10,"dob":"1961-05-27","debut":1988,"bio":"Piloto francés que disputó algunos GPs con Larrousse, Coloni y Rial."},
"JYR":{"name":"Jyrki Järvilehto","nat":"Finlandia","flag":"fi","num":29,"dob":"1966-01-31","debut":1989,"bio":"Piloto finlandés también conocido como JJ Lehto. Disputó algunos GPs con Onyx en 1989."}
};

// ============ TEAMS INFO (datos fijos) ============
// Los IDs son los códigos cortos usados en SEASONS.constructors
const TEAMS_INFO={
"MER":{name:"Mercedes-AMG Petronas",displayName:"MERCEDES",base:"Brackley, Reino Unido",principal:"Toto Wolff",founded:2010,engine:"Mercedes",bio:"Ocho títulos consecutivos de constructores (2014-2021). Volvió a sus raíces Silver Arrows en 2026 con una dupla Russell/Antonelli."},
"RBR":{name:"Oracle Red Bull Racing",displayName:"RED BULL",base:"Milton Keynes, Reino Unido",principal:"Laurent Mekies",founded:2005,engine:"Honda RBPT",bio:"Cuatro títulos de constructores. Dominio con Verstappen entre 2022 y 2024. Motor propio (Red Bull Powertrains) desde 2026."},
"FER":{name:"Scuderia Ferrari",displayName:"FERRARI",base:"Maranello, Italia",principal:"Frédéric Vasseur",founded:1950,engine:"Ferrari",bio:"La escudería más antigua y laureada de la F1 con 16 títulos de constructores. Fichó a Hamilton en 2025."},
"MCL":{name:"McLaren F1 Team",displayName:"McLAREN",base:"Woking, Reino Unido",principal:"Andrea Stella",founded:1966,engine:"Mercedes",bio:"Nueve títulos de constructores. Regresó al tope con la dupla Norris/Piastri, ganando el título en 2024 y 2025."},
"AMR":{name:"Aston Martin Aramco F1",displayName:"ASTON MARTIN",base:"Silverstone, Reino Unido",principal:"Andy Cowell",founded:2021,engine:"Mercedes / Honda (2026)",bio:"Renombrado desde Racing Point en 2021. Propiedad de Lawrence Stroll. Adrian Newey se incorporó en 2025."},
"ALP":{name:"BWT Alpine F1 Team",displayName:"ALPINE",base:"Enstone, Reino Unido",principal:"Steve Nielsen",founded:2021,engine:"Renault / Mercedes (2026)",bio:"Heredero de Lotus/Renault. Renombrado Alpine en 2021. Ganó el GP de Hungría 2021 con Ocon."},
"WIL":{name:"Williams Racing",displayName:"WILLIAMS",base:"Grove, Reino Unido",principal:"James Vowles",founded:1977,engine:"Mercedes",bio:"Nueve títulos de constructores. Propiedad de Dorilton Capital desde 2020. Reconstrucción en curso con Sainz y Albon."},
"HAS":{name:"MoneyGram Haas F1 Team",displayName:"HAAS",base:"Kannapolis, EE.UU.",principal:"Ayao Komatsu",founded:2016,engine:"Ferrari",bio:"Único equipo estadounidense del grid. Dirigido por Ayao Komatsu desde 2024."},
"SAU":{name:"Stake F1 Team Kick Sauber",displayName:"SAUBER",base:"Hinwil, Suiza",principal:"Jonathan Wheatley",founded:1993,engine:"Ferrari",bio:"Equipo suizo histórico. Corrió como Alfa Romeo entre 2019 y 2023. Se convirtió en Audi en 2026."},
"AUD":{name:"Audi F1 Team",displayName:"AUDI",base:"Hinwil, Suiza",principal:"Jonathan Wheatley",founded:2026,engine:"Audi",bio:"Primera aparición de Audi como equipo de F1 tras la compra de Sauber. Dupla Hülkenberg/Bortoleto en su debut."},
"ARO":{name:"Alfa Romeo Racing",displayName:"ALFA ROMEO",base:"Hinwil, Suiza",principal:"Frédéric Vasseur",founded:2019,engine:"Ferrari",bio:"Nombre usado por Sauber entre 2019 y 2023 bajo acuerdo de patrocinio con Alfa Romeo."},
"ATR":{name:"Scuderia AlphaTauri",displayName:"ALPHATAURI",base:"Faenza, Italia",principal:"Franz Tost",founded:2020,engine:"Honda",bio:"Equipo B de Red Bull. Nombre usado entre 2020 y 2023 antes de rebrandearse como Racing Bulls."},
"RBT":{name:"Visa Cash App Racing Bulls",displayName:"RACING BULLS",base:"Faenza, Italia",principal:"Alan Permane",founded:2024,engine:"Honda RBPT",bio:"Equipo B de Red Bull (antes AlphaTauri). Renombrado en 2024. Alan Permane asumió como director en 2025."},
"CAD":{name:"Cadillac F1 Team",displayName:"CADILLAC",base:"Fishers, EE.UU.",principal:"Graeme Lowdon",founded:2026,engine:"Ferrari",bio:"Nueva incorporación al grid de F1 en 2026. Propiedad de TWG Motorsports (General Motors). Debutó con la dupla Bottas/Pérez."}
};
